// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChH3Q5z2uQ6wKOB5-w6NkP4yqBV32v7w4',
    appId: '1:666083983625:web:f7ad67aeb538a6dded53d8',
    messagingSenderId: '666083983625',
    projectId: 'hellotest-d9962',
    databaseURL: 'https://hellotest-d9962-default-rtdb.firebaseio.com/',
    authDomain: 'hellotest-d9962.firebaseapp.com',
    storageBucket: 'hellotest-d9962.appspot.com',
    measurementId: 'G-06LTS3ZPKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAZpe9XmeZHhYiEDwleUvaA2HX7_AFTX8',
    appId: '1:666083983625:android:8ac76ab03fee601ded53d8',
    messagingSenderId: '666083983625',
    projectId: 'hellotest-d9962',
    storageBucket: 'hellotest-d9962.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCA8Ljnc37eNd75oBiX6OCRflMJwhbsqo',
    appId: '1:666083983625:ios:c5d6877b070cccf3ed53d8',
    messagingSenderId: '666083983625',
    projectId: 'hellotest-d9962',
    storageBucket: 'hellotest-d9962.appspot.com',
    iosBundleId: 'com.example.contact',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCA8Ljnc37eNd75oBiX6OCRflMJwhbsqo',
    appId: '1:666083983625:ios:c5d6877b070cccf3ed53d8',
    messagingSenderId: '666083983625',
    projectId: 'hellotest-d9962',
    storageBucket: 'hellotest-d9962.appspot.com',
    iosBundleId: 'com.example.contact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChH3Q5z2uQ6wKOB5-w6NkP4yqBV32v7w4',
    appId: '1:666083983625:web:65397562a65eaa0bed53d8',
    messagingSenderId: '666083983625',
    projectId: 'hellotest-d9962',
    authDomain: 'hellotest-d9962.firebaseapp.com',
    storageBucket: 'hellotest-d9962.appspot.com',
    measurementId: 'G-XFR60NBLWF',
  );
}
